---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: harbor.xirion.net/hub/library/golang
    commands:
      - go build
      - go test -race ./...

  - name: kaniko
    image: harbor.xirion.net/hub/banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: harbor.xirion.net
      repo: library/counter
      tags: latest
      build_args:
        - GIT_SHA=${DRONE_COMMIT}
