---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: harbor.xirion.net/hub/library/golang
    environment:
      ETCDHOST: etcd:2379
      REDISHOST: redis:6379
    commands:
      - go build
      - go test -v -race ./...

  - name: kaniko
    image: harbor.xirion.net/hub/banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: harbor.xirion.net
      repo: library/counter
      tags: latest
      build_args:
        - GIT_SHA=${DRONE_COMMIT}

services:
  - name: redis
    image: harbor.xirion.net/hub/library/redis
  - name: etcd
    image: harbor.xirion.net/library/etcd:v3.3.25
    command:
      - /bin/sh
      - -c
      - |
        exec etcd \
        --data-dir=/data \
        --name node1 \
        --initial-advertise-peer-urls http://0.0.0.0:2380 \
        --listen-peer-urls http://0.0.0.0:2380
        --advertise-client-urls http://0.0.0.0:2379 \
        --listen-client-urls http://0.0.0.0:2379 \
        --initial-cluster node1=http://0.0.0.0:2380 \
        --log-level info
